Nova demo requires USB HID driver of dde_linux
Following the instructions of the "Getting started" chapter, "A simple
system scenario" section, "Targeting a microkernel" paragraph, an error
occurs when running "make run/demo KERNEL=nova BOARD=pc", namely:

	$ make run/demo KERNEL=nova BOARD=pc
	including /home/u/Desktop/genode_play/genode/tool/run/power_on/qemu
	including /home/u/Desktop/genode_play/genode/tool/run/log/qemu
	including /home/u/Desktop/genode_play/genode/tool/run/image/iso
	including /home/u/Desktop/genode_play/genode/tool/run/boot_dir/nova
	including /home/u/Desktop/genode_play/genode/repos/os/run/demo.run
	update depot: /home/u/Desktop/genode_play/genode/tool/depot/create genodelabs/bin/x86_64/base-nova genodelabs/bin/x86_64/demo genodelabs/bin/x86_64/global_keys_handler genodelabs/bin/x86_64/init genodelabs/bin/x86_64/nit_focus genodelabs/bin/x86_64/nitpicker genodelabs/bin/x86_64/report_rom genodelabs/bin/x86_64/rom_filter genodelabs/pkg/x86_64/drivers_interactive-pc CROSS_DEV_PREFIX=/usr/local/genode/tool/21.05/bin/genode-x86- DEPOT_DIR=/home/u/Desktop/genode_play/genode/depot UPDATE_VERSIONS=1 FORCE=1 REBUILD=
	make[1]: Entering directory '/home/u/Desktop/genode_play/genode/build/x86_64'
	Error: incomplete or missing recipe (genodelabs/src/usb_hid_drv genodelabs/src/usb_host_drv)

This commit adds instructions for including the dde_linux source-code
repository in the build to resolve this issue, and preparing the download
of said source code.